Adding immutableX example
Web3Auth/examples pull request #23
Opened 2022-11-08 03:54 UTC by Saviour1001

2022-11-08 06:48 UTC, shahbaz17 commented on web-modal-sdk/immutableX/react-immutable-web3auth-example/src/App.tsx
> +        & ReactJS Example
Please update the name of the app here.

2022-11-08 06:49 UTC, shahbaz17 requested changes

2022-11-08 06:49 UTC, shahbaz17 commented on web-modal-sdk/immutableX/react-immutable-web3auth-example/src/App.tsx
> +    uiConsole(response);
Response is empty here.

2022-11-08 07:38 UTC, Saviour1001 commented on web-modal-sdk/immutableX/react-immutable-web3auth-example/src/App.tsx
> +    uiConsole(response);
Changed the response which shows up

2022-11-08 15:35 UTC, shahbaz17 requested changes

2022-11-08 15:35 UTC, shahbaz17 commented on web-modal-sdk/immutableX/react-immutableX-web3auth-example/README.md
> +# Web3Auth x React Demo Application
This still needs to change @Saviour1001

2022-11-08 15:35 UTC, shahbaz17 commented on web-modal-sdk/immutableX/react-immutableX-web3auth-example/src/App.tsx
> +          Web3Auth{" "}
Here too, please add ImmutableX.

2022-11-08 15:35 UTC, shahbaz17 commented on web-modal-sdk/immutableX/react-immutableX-web3auth-example/src/immutableRPC.ts
> +      if (response.tx_hash) {
What could be the `else` statement here? If this fails?

Should we address that?

2022-11-09 08:12 UTC, shahbaz17 approved these changes
LGTM

2022-11-09 09:51 UTC, merged